/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controldenotas;

import java.text.DecimalFormat;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jvane
 */
public class ControlNotasFrame extends javax.swing.JFrame {

    /**
     * Creates new form ControlNotasFrame
     */
    public ControlNotasFrame() {
        initComponents();
        super.setTitle("ControlNotas");
        tfCUM.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lbCarrera = new javax.swing.JLabel();
        cbListaCarreras = new javax.swing.JComboBox<>();
        lbCiclo = new javax.swing.JLabel();
        cbListaCiclo = new javax.swing.JComboBox<>();
        lbCUM = new javax.swing.JLabel();
        tfCUM = new javax.swing.JTextField();
        lbMateria = new javax.swing.JLabel();
        cbMateria1 = new javax.swing.JComboBox<>();
        cbMateria2 = new javax.swing.JComboBox<>();
        cbMateria3 = new javax.swing.JComboBox<>();
        cbMateria4 = new javax.swing.JComboBox<>();
        cbMateria5 = new javax.swing.JComboBox<>();
        lbUV = new javax.swing.JLabel();
        cbUV1 = new javax.swing.JComboBox<>();
        cbUV2 = new javax.swing.JComboBox<>();
        cbUV3 = new javax.swing.JComboBox<>();
        cbUV4 = new javax.swing.JComboBox<>();
        cbUV5 = new javax.swing.JComboBox<>();
        lbNota = new javax.swing.JLabel();
        tfNota1 = new javax.swing.JTextField();
        tfNota2 = new javax.swing.JTextField();
        tfNota3 = new javax.swing.JTextField();
        tfNota4 = new javax.swing.JTextField();
        tfNota5 = new javax.swing.JTextField();
        lbTEstado = new javax.swing.JLabel();
        lbEstado1 = new javax.swing.JLabel();
        lbEstado2 = new javax.swing.JLabel();
        lbEstado3 = new javax.swing.JLabel();
        lbEstado4 = new javax.swing.JLabel();
        lbEstado5 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        lbCalcular = new javax.swing.JLabel();
        lbimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTitulo.setText("CONTROL DE NOTAS");

        lbNombre.setText("Nombre:");

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        lbCarrera.setText("Carrera:");

        cbListaCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Ing. Sistemas", "Ing. Electrica", "Ing. Industrial", "Ing. Agronegocios" }));
        cbListaCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListaCarrerasActionPerformed(evt);
            }
        });

        lbCiclo.setText("Ciclo:");

        cbListaCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "01", "02" }));
        cbListaCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListaCicloActionPerformed(evt);
            }
        });

        lbCUM.setText("CUM");

        tfCUM.setEditable(false);
        tfCUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCUMActionPerformed(evt);
            }
        });

        lbMateria.setText("Materia");

        cbMateria1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cbMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Investigacion de Operaciones I", "Electronica", "Legislacion Aplicada a la Empresa", "Desarrollo de Software", "Base de Datos II" }));

        cbMateria2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cbMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Investigacion de Operaciones I", "Electronica", "Legislacion Aplicada a la Empresa", "Desarrollo de Software", "Base de Datos II" }));
        cbMateria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria2ActionPerformed(evt);
            }
        });

        cbMateria3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cbMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Investigacion de Operaciones I", "Electronica", "Legislacion Aplicada a la Empresa", "Desarrollo de Software", "Base de Datos II" }));

        cbMateria4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cbMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Investigacion de Operaciones I", "Electronica", "Legislacion Aplicada a la Empresa", "Desarrollo de Software", "Base de Datos II" }));

        cbMateria5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Investigacion de Operaciones I", "Electronica", "Legislacion Aplicada a la Empresa", "Desarrollo de Software", "Base de Datos II" }));

        lbUV.setText("UV");

        cbUV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4", " " }));
        cbUV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUV1ActionPerformed(evt);
            }
        });

        cbUV2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4", " " }));

        cbUV3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4", " " }));

        cbUV4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4", " " }));

        cbUV5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4" }));
        cbUV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUV5ActionPerformed(evt);
            }
        });

        lbNota.setText("Nota");

        tfNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota1ActionPerformed(evt);
            }
        });

        lbTEstado.setText("Estado");

        lbEstado1.setText("Estado");

        lbEstado2.setText("Estado");

        lbEstado3.setText("Estado");

        lbEstado4.setText("Estado");

        lbEstado5.setText("Estado");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        lbimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controldenotas/imagen.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(289, 289, 289)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(lbMateria))
                                .addComponent(cbMateria4, 0, 1, Short.MAX_VALUE)
                                .addComponent(cbMateria3, 0, 1, Short.MAX_VALUE)
                                .addComponent(cbMateria2, 0, 1, Short.MAX_VALUE)
                                .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbMateria5, 0, 1, Short.MAX_VALUE))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbUV2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbUV1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbUV5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbUV4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbUV3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbEstado5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbTEstado))
                            .addGap(84, 84, 84))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(lbNombre)
                            .addGap(147, 147, 147)
                            .addComponent(lbCarrera)
                            .addGap(108, 108, 108)
                            .addComponent(lbCiclo)
                            .addGap(91, 91, 91)
                            .addComponent(lbCUM))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(lbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(17, 17, 17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTitulo)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbUV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cbListaCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(47, 47, 47)
                                            .addComponent(cbListaCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addComponent(tfCUM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(63, 63, 63)
                                            .addComponent(lbNota)))))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btCalcular)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbCarrera)
                    .addComponent(lbCiclo)
                    .addComponent(lbCUM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbListaCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbListaCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMateria)
                            .addComponent(lbTEstado)
                            .addComponent(lbUV)
                            .addComponent(lbNota))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbimagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 21, Short.MAX_VALUE)
                        .addComponent(btCalcular)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbUV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUV5ActionPerformed

    private void tfNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota1ActionPerformed

    private void cbListaCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListaCicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbListaCicloActionPerformed

    private void tfCUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCUMActionPerformed

    private void cbMateria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria2ActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        
        String Nombre = tfNombre.getText();
        String NombreA = ""; //para la vaiable bandera
        String Carrera = "";//para la vaiable bandera
        String CarreraSeleccionada = (String)this.cbListaCarreras.getSelectedItem();
        String Ciclo = "";//para la vaiable bandera
        String CicloSeleccionado = (String)this.cbListaCiclo.getSelectedItem();
        JComboBox[] Materias = {cbMateria1, cbMateria2, cbMateria3, cbMateria4, cbMateria5};//Para hacer de una las validadciones de las materias
        String MateriaA="";//para la vaiable bandera
        JComboBox[] UV = {cbUV1, cbUV2, cbUV3, cbUV4, cbUV5};//Para hacer de una las validadciones de las UV
        String UVa="";//para la vaiable bandera
        JTextField[] Notas = {tfNota1, tfNota2, tfNota3, tfNota4, tfNota5};//Para hacer de una las validadciones de las notas
        String NotasA="";//para la vaiable bandera
        double notaP; //Para parsearla
        double UVp;//Para parsearla
        double AlmacenNotaUV=0.00;
        double AlmacenUV=0.00;
        JLabel[] Estados = {lbEstado1, lbEstado2, lbEstado3, lbEstado4, lbEstado5};// servira para las notas aprobadas
        int cA = 0;//contadores
        int cR = 0;//contadores
        double CUM=0.00; 
        String CUMtf="";//cum pasado a string para mostrarlo en tf
        
       //Validacion de Nombre
       if(Nombre.isEmpty()){
           NombreA = "-1";
           JOptionPane.showMessageDialog(this, "Digite un nombre", "Error",JOptionPane.ERROR_MESSAGE);
       }
       
       //Validacon Carrera
       if("-".equals(CarreraSeleccionada)){
           Carrera="-1";
           JOptionPane.showMessageDialog(this, "Seleccione una carrera","Error",JOptionPane.ERROR_MESSAGE);
       }
       
       //Validacion Ciclos
       if("-".equals(CicloSeleccionado)){
           Ciclo="-1";
           JOptionPane.showMessageDialog(this, "Seleccione un ciclo","Error", JOptionPane.ERROR_MESSAGE);
       }
       
       //Validacion Materias
       for(int i=0;i<5;i++){
           if("-".equals(Materias[i].getSelectedItem())){
               MateriaA="-1";
               JOptionPane.showMessageDialog(this,"Seleccione una materia en la casilla "+(i+1), "Error", JOptionPane.ERROR_MESSAGE);
           }
       }
       
       //Validacon UV
       for(int i=0;i<5;i++){
           if("0".equals(UV[i].getSelectedItem())){
               UVa="-1";
               JOptionPane.showMessageDialog(this,"Seleccione una UV en la casilla "+(i+1), "Error", JOptionPane.ERROR_MESSAGE);
           }
       }
       
       //Validacion notas
       for(int i=0;i<5;i++){
           if(Notas[i].getText().isEmpty()){
               NotasA="-1";
               JOptionPane.showMessageDialog(this, "Digite la nota de la casilla "+(i+1),"Error",JOptionPane.ERROR_MESSAGE);
           }
       }
       
       //Estados Aprobados o Reprobados
       for(int i=0;i<5;i++){
           notaP=Double.parseDouble(Notas[i].getText());
           if(notaP<6 && notaP>-1){
               Estados[i].setText("Reprobado");
               cR++;
           }else if(notaP>5 && notaP<11){
                    Estados[i].setText("Aprobado");
                    cA++;
           }else{
               Estados[i].setText("Estado");
           }
       }
       //Calculo CUM
       
       for(int i=0;i<5;i++){
           notaP=Double.parseDouble(Notas[i].getText());;
           UVp=Double.parseDouble(UV[i].getSelectedItem().toString());
           AlmacenNotaUV+=(notaP*UVp);
           AlmacenUV+=UVp;
           
           CUM=AlmacenNotaUV/AlmacenUV;
           
           // para dejar cum en formato de 2 decimales
           DecimalFormat formato = new DecimalFormat("#.##");
           
           CUMtf=formato.format(CUM);
           
           
           tfCUM.setText(CUMtf);
           
       }
       //Para el label del final
       if(!"-1".equals(NombreA) && !"-1".equals(Carrera)&& !"-1".equals(Ciclo)&& !"-1".equals(MateriaA)&& !"-1".equals(UVa)&& !"-1".equals(NotasA)){
            lbCalcular.setText(Nombre + " su estado actual es de "
                    +cA+" materias aprobadas y "
                    +cR+" materias reprobadas y su CUM actual es de "
                    +CUM
            );

        //lbCalcular.setText(Nombre + " su estado actual es de "+i+" materias aprobadas y "+j+" materias reprobadas y su CUM actual es de "+CUM);
       }
    }//GEN-LAST:event_btCalcularActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfNombreActionPerformed

    private void cbListaCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListaCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbListaCarrerasActionPerformed

    private void cbUV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUV1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlNotasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlNotasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlNotasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlNotasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlNotasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JComboBox<String> cbListaCarreras;
    private javax.swing.JComboBox<String> cbListaCiclo;
    private javax.swing.JComboBox<String> cbMateria1;
    private javax.swing.JComboBox<String> cbMateria2;
    private javax.swing.JComboBox<String> cbMateria3;
    private javax.swing.JComboBox<String> cbMateria4;
    private javax.swing.JComboBox<String> cbMateria5;
    private javax.swing.JComboBox<String> cbUV1;
    private javax.swing.JComboBox<String> cbUV2;
    private javax.swing.JComboBox<String> cbUV3;
    private javax.swing.JComboBox<String> cbUV4;
    private javax.swing.JComboBox<String> cbUV5;
    private javax.swing.JLabel lbCUM;
    private javax.swing.JLabel lbCalcular;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCiclo;
    private javax.swing.JLabel lbEstado1;
    private javax.swing.JLabel lbEstado2;
    private javax.swing.JLabel lbEstado3;
    private javax.swing.JLabel lbEstado4;
    private javax.swing.JLabel lbEstado5;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNota;
    private javax.swing.JLabel lbTEstado;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUV;
    private javax.swing.JLabel lbimagen;
    private javax.swing.JTextField tfCUM;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNota1;
    private javax.swing.JTextField tfNota2;
    private javax.swing.JTextField tfNota3;
    private javax.swing.JTextField tfNota4;
    private javax.swing.JTextField tfNota5;
    // End of variables declaration//GEN-END:variables
}
